"""citizen_reports

Revision ID: 2213c99ed3a2
Revises: d7eb8f22aa38
Create Date: 2026-08-08 04:12:39.782821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2213c99ed3a2'
down_revision: Union[str, Sequence[str], None] = 'd7eb8f22aa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=16), nullable=False),
    sa.Column('place_name', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('mask_status', sa.String(length=16), nullable=False),
    sa.Column('mask_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=255), nullable=False),
    sa.Column('usable_for_training', sa.Boolean(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_created', 'citizen_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_report_status', 'citizen_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_status', table_name='citizen_reports')
    op.drop_index('ix_report_created', table_name='citizen_reports')
    op.drop_table('citizen_reports')
    # ### end Alembic commands ###
