"""road_inspections per_100m 구간 보정 밀도

Revision ID: 360aa4ff3b21
Revises: d7fb4badf051
Create Date: 2026-08-15 21:25:10.889442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360aa4ff3b21'
down_revision: Union[str, Sequence[str], None] = 'd7fb4badf051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_inspections', sa.Column('per_100m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_inspections', 'per_100m')
    # ### end Alembic commands ###
