"""road_inspections 노면 점검 이력

Revision ID: 74e534acf561
Revises: 81b687282d9d
Create Date: 2026-08-14 09:38:29.170338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e534acf561'
down_revision: Union[str, Sequence[str], None] = '81b687282d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('camera_name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('defect_count', sa.Integer(), nullable=False),
    sa.Column('frames_analyzed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_inspections_analyzed_at'), 'road_inspections', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_road_inspections_camera_id'), 'road_inspections', ['camera_id'], unique=False)
    op.create_index('ix_road_inspections_camera_time', 'road_inspections', ['camera_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_road_inspections_camera_time', table_name='road_inspections')
    op.drop_index(op.f('ix_road_inspections_camera_id'), table_name='road_inspections')
    op.drop_index(op.f('ix_road_inspections_analyzed_at'), table_name='road_inspections')
    op.drop_table('road_inspections')
    # ### end Alembic commands ###
