"""facility_controls

Revision ID: d7eb8f22aa38
Revises: 667d7b9a3ffe
Create Date: 2026-08-08 00:00:49.321749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eb8f22aa38'
down_revision: Union[str, Sequence[str], None] = '667d7b9a3ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('facility_name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facility_created', 'facility_controls', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_facility_created', table_name='facility_controls')
    op.drop_table('facility_controls')
    # ### end Alembic commands ###
