"""error_codes, error_logs 오류 관리

Revision ID: d7fb4badf051
Revises: 74e534acf561
Create Date: 2026-08-14 15:36:39.971956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fb4badf051'
down_revision: Union[str, Sequence[str], None] = '74e534acf561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_error_codes_category', 'error_codes', ['category'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_code'), 'error_logs', ['code'], unique=False)
    op.create_index('ix_error_logs_code_time', 'error_logs', ['code', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_error_logs_fingerprint'), 'error_logs', ['fingerprint'], unique=False)
    op.create_index('ix_error_logs_fp_resolved', 'error_logs', ['fingerprint', 'resolved'], unique=False)
    op.create_index(op.f('ix_error_logs_last_seen_at'), 'error_logs', ['last_seen_at'], unique=False)
    op.create_index('ix_error_logs_resolved_time', 'error_logs', ['resolved', 'last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_logs_resolved_time', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_last_seen_at'), table_name='error_logs')
    op.drop_index('ix_error_logs_fp_resolved', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_fingerprint'), table_name='error_logs')
    op.drop_index('ix_error_logs_code_time', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_code'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('ix_error_codes_category', table_name='error_codes')
    op.drop_table('error_codes')
    # ### end Alembic commands ###
