"""users: must_change_password

Revision ID: f58f8822b3f4
Revises: b93ae00191f5
Create Date: 2026-08-07 17:41:10.827677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58f8822b3f4'
down_revision: Union[str, Sequence[str], None] = 'b93ae00191f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행에 채울 값이 필요하므로 server_default 를 준다. 기존 계정은
    # 이미 본인이 쓰던 비밀번호이므로 변경 강제 대상이 아니다(False).
    op.add_column('users',
                  sa.Column('must_change_password', sa.Boolean(),
                            nullable=False, server_default=sa.false()))
    # 기본값은 애플리케이션이 정하므로 DDL 기본값은 걷어낸다.
    op.alter_column('users', 'must_change_password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
